#!/bin/bash

# hard coded source and destination etc
# either have as variable or read some config file ... for laters ...

src="/"
user="root"
server="hc2"
dest="/mnt/WDred/t470s_distributions"
excl="/home/rob/.config/rsyncincbak/sys_bak_excludes"
dt=$(date +%Y%m%d_%H%M%S)
froot="t470s-arch-sysbackup"
keep=5
all_ok="yes"
stage="prelim"

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
        echo "** Trapped CTRL-C"
	if [ "$stage" == "prelim" ]; then
		echo "** exiting now"
		exit
	fi
	echo "** deleting failed backup folder then going to exit.."
	all_ok="no"	
}

if filels="$(ssh $user@$server ls -d "$dest/[0-9]*-$froot-[0-9][0-9][0-9][0-9][0-9][0-9]" 2>/dev/null)"; then
	echo "incrementing backup"
	max=$(( -1 ))
	min=$(( 999999 ))
	count=$(( 0 ))
	linkdir="empty"
	for f in $filels; do
		inc="$(echo $f | awk 'BEGIN { FS = "-" } ; {print $NF}')"
		a=$(( 10#$inc ))
		if (( $a > $max )); then
			max=$a
			linkdir="$f"	
		fi
		if (( $a < $min )); then
			min=$a
		fi
		let count++
	done

	echo "initialising backup"

	new_inc=$(( $max+1 ))
	new_pad="$(printf %06d "$new_inc")"
	newdir="$dest/$dt-$froot-$new_pad"

	stage="rsync"

	echo "starting $stage"
	echo "   server: $server"
	echo "   user: $user"
	echo "   hard linking to: $linkdir"
	echo "   source: $src"
	echo "   destination: $newdir"
	rsync -aAXPh --delete --delay-updates --info=name1 --info=progress2 --exclude-from="$excl" --link-dest="$linkdir" "$src" "$user"@"$server":"$newdir"
	exit_code=$?
	
	if [ "$all_ok" == "no" ] || (( exit_code > 1 )); then
		ssh "$user"@"$server" rm -rf "$newdir" 2>/dev/null
		echo "**"
		echo "** something has gone wrong"
		echo "**"
		echo "** removed rsync created directory from server"
		echo "**"
		echo "** now exiting"
		exit
	fi

	
	echo ""
	echo "-------------------------------------"
	echo ""
	echo "   Hard links created to: $linkdir"

	if (( $count  >= $keep )); then
		del_inc="$(printf %06d "$min")"
		deldir="$dest/[0-9]*-$froot-$del_inc"
		echo ""
		echo "   Deleting old backup: $deldir"
		ssh $user@$server rm -rf $deldir
	fi
	echo ""
	echo "-------------------------------------"
	echo ""
	echo "FINISHED"
	echo ""
	echo "-------------------------------------"
else
	echo "new folder... initialising"
	newdir="$dest/$dt-$froot-000000"
	#ssh $user@$server mkdir -p "$newdir" 
	stage="rsync"
	rsync -aAXPh --delete --info=name0 --info=progress2 --exclude-from="$excl" "$src" "$user"@"$server":"$newdir"
fi
